/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0e0e0e",
        "primary-fixed-dim": "#24f07e",
        "tertiary-fixed-dim": "#00cdec",
        "on-primary-container": "#004f24",
        error: "#ff716c",
        "secondary-dim": "#65ecae",
        "inverse-primary": "#006e35",
        "surface-dim": "#0e0e0e",
        "surface-container": "#1a1919",
        "tertiary-fixed": "#00dcfd",
        "on-secondary-fixed-variant": "#006945",
        "on-error-container": "#ffa8a3",
        "on-tertiary-container": "#004955",
        "tertiary-dim": "#00cdec",
        "on-tertiary-fixed-variant": "#005361",
        "surface-tint": "#3fff8b",
        "inverse-on-surface": "#565554",
        "surface-container-highest": "#262626",
        "secondary-container": "#006c47",
        "tertiary-container": "#00dcfd",
        "on-surface": "#ffffff",
        "on-tertiary": "#005360",
        "on-secondary-container": "#e1ffeb",
        "primary-fixed": "#3fff8b",
        "outline-variant": "#494847",
        "error-container": "#9f0519",
        "on-primary-fixed": "#004820",
        "on-error": "#490006",
        primary: "#3fff8b",
        tertiary: "#7ae6ff",
        "surface-container-low": "#131313",
        secondary: "#74fbbb",
        "on-background": "#ffffff",
        surface: "#0e0e0e",
        "surface-container-high": "#201f1f",
        "error-dim": "#d7383b",
        "on-primary": "#005d2c",
        "primary-dim": "#24f07e",
        outline: "#777575",
        "surface-container-lowest": "#000000",
        "surface-bright": "#2c2c2c",
        "secondary-fixed": "#74fbbb",
        "secondary-fixed-dim": "#65ecae",
        "on-surface-variant": "#adaaaa",
        "inverse-surface": "#fcf8f8",
        "on-secondary-fixed": "#00492f",
        "on-primary-fixed-variant": "#006832",
        "surface-variant": "#262626",
        "on-secondary": "#005e3d",
        "on-tertiary-fixed": "#00343d",
        "primary-container": "#13ea79",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
